fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
    apt:
      repo: "puppetlabs/apt"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
    epel:
      repo: "puppet/epel"
    augeasproviders_core:
      repo: "herculesteam/augeasproviders_core"
    augeasproviders_sysctl:
      repo: "herculesteam/augeasproviders_sysctl"
  repositories:
    easyrsa:
      repo: 'https://github.com/rehanone/puppet-easyrsa.git'
      ref: '0.7.0'
  symlinks:
    openvpn: "#{source_dir}"
